@startuml
'https://plantuml.com/class-diagram

class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    - {static} instance:HeroAircraft
    + {static} getInstance():HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
    + setShootNum(int shootNum):void
}

@enduml